version: "3.8"

services:
  app:
    image: maven:3.6-jdk-11-slim
    working_dir: /src
    command: mvn -s /usr/share/maven/ref/settings-docker.xml spring-boot:run
    user: "1000"
    ports:
      - "8080:8080"
    volumes:
      - .:/src
      - "$HOME/.m2/repository:/usr/share/maven/ref/repository"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/application
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application
      PGDATA: /var/lib/postgresql/data/pgadata
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: